// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0t_cCUNW4yYS3i4Ea2T9_MmQzTD-IHjM',
    appId: '1:36614087048:web:4bc43305e4cdf5eade1a3d',
    messagingSenderId: '36614087048',
    projectId: 'springboot-firebase-26557',
    authDomain: 'springboot-firebase-26557.firebaseapp.com',
    storageBucket: 'springboot-firebase-26557.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxhFp47SAkAoImfzrxHDkS1vOk1FrzwFo',
    appId: '1:36614087048:android:b5cb5cc47b08006ede1a3d',
    messagingSenderId: '36614087048',
    projectId: 'springboot-firebase-26557',
    storageBucket: 'springboot-firebase-26557.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRFb8Lqrt4O0fGg08uA4FRkjXPklcPio',
    appId: '1:36614087048:ios:6bf03abd963c7301de1a3d',
    messagingSenderId: '36614087048',
    projectId: 'springboot-firebase-26557',
    storageBucket: 'springboot-firebase-26557.appspot.com',
    iosBundleId: 'com.example.tokenfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRFb8Lqrt4O0fGg08uA4FRkjXPklcPio',
    appId: '1:36614087048:ios:6bf03abd963c7301de1a3d',
    messagingSenderId: '36614087048',
    projectId: 'springboot-firebase-26557',
    storageBucket: 'springboot-firebase-26557.appspot.com',
    iosBundleId: 'com.example.tokenfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0t_cCUNW4yYS3i4Ea2T9_MmQzTD-IHjM',
    appId: '1:36614087048:web:9ef38b8dcc976130de1a3d',
    messagingSenderId: '36614087048',
    projectId: 'springboot-firebase-26557',
    authDomain: 'springboot-firebase-26557.firebaseapp.com',
    storageBucket: 'springboot-firebase-26557.appspot.com',
  );
}
